# Week 2 – Assignment

**Intern:** Soham S. Deshmukh

**Objective**

The objective of this assignment is to analyze the provided sales dataset using SQL. The analysis includes loading the dataset into a SQLite database, exploring the data, applying filtering and aggregation techniques, solving business-related queries, validating data quality, and summarizing the key findings.

## Importing Required Libraries

The required Python libraries are imported to load the dataset, create a SQLite database, and execute SQL queries within the notebook.

In [85]:
import pandas as pd
import sqlite3

## Loading the Dataset

The provided Superstore dataset is loaded into a Pandas DataFrame. Before performing SQL analysis, the dataset is explored to understand its structure and verify that it has been loaded correctly.

In [86]:
df = pd.read_csv("../dataset/Sample - Superstore.csv", encoding="latin1")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

## Exploring the Dataset

Before importing the dataset into SQLite, a few basic checks are performed to understand the available data and verify its quality.

In [87]:
df.shape

(9994, 21)

In [88]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [89]:
df.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [90]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [91]:
df.duplicated().sum()

np.int64(0)

In [92]:
df.sample(5, random_state=42)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
3125,3126,CA-2015-121720,6/11/2015,6/12/2015,First Class,JE-15610,Jim Epp,Corporate,United States,Lakeland,...,33801,South,OFF-ST-10003816,Office Supplies,Storage,Fellowes High-Stak Drawer Files,563.808,4,0.2,21.1428
1441,1442,CA-2017-128160,12/19/2017,12/24/2017,Second Class,MM-17920,Michael Moore,Consumer,United States,San Francisco,...,94110,West,OFF-BI-10001510,Office Supplies,Binders,Deluxe Heavy-Duty Vinyl Round Ring Binder,36.672,2,0.2,11.4600
4510,4511,CA-2016-119935,11/10/2016,11/14/2016,Standard Class,KM-16225,Kalyca Meade,Corporate,United States,Springfield,...,65807,Central,FUR-FU-10001085,Furniture,Furnishings,3M Polarizing Light Filter Sleeves,37.300,2,0.0,17.1580
39,40,CA-2015-117415,12/27/2015,12/31/2015,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,...,77041,Central,FUR-CH-10004218,Furniture,Chairs,"Global Fabric Manager's Chair, Dark Gray",212.058,3,0.3,-15.1470
4509,4510,CA-2017-167003,5/23/2017,5/29/2017,Standard Class,VS-21820,Vivek Sundaresam,Consumer,United States,Los Angeles,...,90036,West,FUR-TA-10001520,Furniture,Tables,"Lesro Sheffield Collection Coffee Table, End T...",171.288,3,0.2,-6.4233

## Creating the SQLite Database

A SQLite database is created to store the dataset and execute SQL queries throughout the assignment.

In [93]:
conn = sqlite3.connect("superstore.db")
cursor = conn.cursor()

print("Database connection established successfully.")

Database connection established successfully.

## Importing the Dataset into SQLite

The dataset is imported into the SQLite database as a table named **superstore**. If the table already exists, it is replaced so that the latest version of the dataset is always used.

In [94]:
df.to_sql("superstore", conn, if_exists="replace", index=False)

print("Dataset imported successfully into SQLite.")

Dataset imported successfully into SQLite.

## Verifying the Imported Table

The following queries are used to confirm that the dataset has been imported successfully and is ready for SQL analysis.

In [95]:
query = """SELECT COUNT(*) AS total_records FROM superstore;"""
pd.read_sql(query, conn)

   total_records
0           9994

In [96]:
query = """PRAGMA table_info(superstore);"""
pd.read_sql(query, conn)

    cid           name     type  notnull dflt_value  pk
0     0         Row ID  INTEGER        0       None   0
1     1       Order ID     TEXT        0       None   0
2     2     Order Date     TEXT        0       None   0
3     3      Ship Date     TEXT        0       None   0
4     4      Ship Mode     TEXT        0       None   0
5     5    Customer ID     TEXT        0       None   0
6     6  Customer Name     TEXT        0       None   0
7     7        Segment     TEXT        0       None   0
8     8        Country     TEXT        0       None   0
9     9           City     TEXT        0       None   0
10   10          State     TEXT        0       None   0
11   11    Postal Code  INTEGER        0       None   0
12   12         Region     TEXT        0       None   0
13   13     Product ID     TEXT        0       None   0
14   14       Category     TEXT        0       None   0
15   15   Sub-Category     TEXT        0       None   0
16   16   Product Name     TEXT        0       None   0
17   17          Sales     REAL        0       None   0
18   18       Quantity  INTEGER        0       None   0
19   19       Discount     REAL        0       None   0
20   20         Profit     REAL        0       None   0

In [97]:
query = """SELECT * FROM superstore LIMIT 5;"""
pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

## Part A - Sales Data Analysis

### Filtering Data

The following queries use the `WHERE` clause to retrieve records based on different business conditions.

**Filter 1** - Orders from the West Region

In [98]:
query = """SELECT * FROM superstore WHERE Category = 'Furniture';"""
pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
3,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
4,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,9963,CA-2015-168088,3/19/2015,3/22/2015,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,...,77041,Central,FUR-BO-10004218,Furniture,Bookcases,Bush Heritage Pine Collection 5-Shelf Bookcase...,383.4656,4,0.32,-67.6704
2117,9965,CA-2016-146374,12/5/2016,12/10/2016,Second Class,HE-14800,Harold Engle,Corporate,United States,Newark,...,19711,East,FUR-FU-10002671,Furniture,Furnishings,Electrix 20W Halogen Replacement Bulb for Zoom...,13.4000,1,0.00,6.4320
2118,9981,US-2015-151435,9/6/2015,9/9/2015,Second Class,SW-20455,Shaun Weien,Consumer,United States,Lafayette,...,70506,South,FUR-TA-10001039,Furniture,Tables,KI Adjustable-Height Table,85.9800,1,0.00,22.3548
2119,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
2120,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332

**Filter 2** - Products under the Furniture Category

In [99]:
query = """SELECT * FROM superstore WHERE Sales > 1000;"""
pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184,9,0.2,85.3092
1,25,CA-2015-106320,9/25/2015,9/30/2015,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,...,84057,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.630,3,0.0,240.2649
2,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430,7,0.5,-1665.0522
3,36,CA-2016-117590,12/8/2016,12/10/2016,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,75080,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544,7,0.2,123.4737
4,55,CA-2016-105816,12/11/2016,12/17/2016,Standard Class,JM-15265,Janet Molinari,Corporate,United States,New York City,...,10024,East,TEC-PH-10002447,Technology,Phones,AT&T CL83451 4-Handset Telephone,1029.950,5,0.0,298.6855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,9867,US-2015-116981,3/26/2015,3/28/2015,Second Class,SM-20950,Suzanne McNair,Corporate,United States,New York City,...,10009,East,OFF-ST-10002615,Office Supplies,Storage,"Dual Level, Single-Width Filing Carts",1085.420,7,0.0,282.2092
464,9926,CA-2015-159534,3/20/2015,3/23/2015,First Class,DH-13075,Dave Hallsten,Corporate,United States,New York City,...,10035,East,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,1087.936,8,0.2,353.5792
465,9930,CA-2016-129630,9/4/2016,9/4/2016,Same Day,IM-15055,Ionia McGrath,Consumer,United States,San Francisco,...,94122,West,TEC-CO-10003763,Technology,Copiers,Canon PC1060 Personal Laser Copier,2799.960,5,0.2,944.9865
466,9948,CA-2017-121559,6/1/2017,6/3/2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,FUR-CH-10003746,Furniture,Chairs,Hon 4070 Series Pagoda Round Back Stacking Chairs,1925.880,6,0.0,539.2464
467,9949,CA-2017-121559,6/1/2017,6/3/2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,OFF-AP-10002945,Office Supplies,Appliances,Honeywell Enviracaire Portable HEPA Air Cleane...,2405.200,8,0.0,793.7160

**Filter 4** - Orders placed during the year 2017

In [100]:
query = """ 
SELECT * FROM superstore
WHERE "Order Date" LIKE '%2017';
"""

pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,13,CA-2017-114412,4/15/2017,4/20/2017,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,...,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3,0.2,5.4432
1,24,US-2017-156909,7/16/2017,7/18/2017,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,19140,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,0.3,-1.0196
2,35,CA-2017-107727,10/19/2017,10/23/2017,Second Class,MA-17560,Matt Abelman,Home Office,United States,Houston,...,77095,Central,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,29.472,3,0.2,9.9468
3,42,CA-2017-120999,9/10/2017,9/15/2017,Standard Class,LC-16930,Linda Cazamias,Corporate,United States,Naperville,...,60540,Central,TEC-PH-10004093,Technology,Phones,Panasonic Kx-TS550,147.168,4,0.2,16.5564
4,44,CA-2017-139619,9/19/2017,9/23/2017,Standard Class,ES-14080,Erin Smith,Corporate,United States,Melbourne,...,32935,South,OFF-ST-10003282,Office Supplies,Storage,"Advantus 10-Drawer Portable Organizer, Chrome ...",95.616,2,0.2,9.5616
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3307,9989,CA-2017-163629,11/17/2017,11/21/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.100,5,0.0,55.6470
3308,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
3309,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
3310,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
3311,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

### Aggregation using GROUP BY

The following queries summarize the sales data using aggregate functions such as `SUM()`, `COUNT()`, and `AVG()`.

In [101]:
#Total Sales by region
query = """
SELECT Region, SUM(Sales) AS total_sales
FROM superstore
GROUP BY Region;
"""

pd.read_sql(query, conn)

    Region  total_sales
0  Central  501239.8908
1     East  678781.2400
2    South  391721.9050
3     West  725457.8245

In [102]:
#Total Quantity sold by category
query = """
SELECT Category, SUM(Quantity) AS total_quantity
FROM superstore
GROUP BY Category;
"""

pd.read_sql(query, conn)

          Category  total_quantity
0        Furniture            8028
1  Office Supplies           22906
2       Technology            6939

In [103]:
#Average Sales by category
query = """
SELECT Category, ROUND(AVG(Sales), 2) AS average_sales
FROM superstore
GROUP BY Category;
"""

pd.read_sql(query, conn)

          Category  average_sales
0        Furniture         349.83
1  Office Supplies         119.32
2       Technology         452.71

### Sorting and Limiting Results

The following queries identify the top-performing products and categories based on sales.

In [104]:
#Top 10 products by sales
query = """
SELECT "Product Name", SUM(Sales) AS total_sales
FROM superstore
GROUP BY "Product Name"
ORDER BY total_sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                                        Product Name  total_sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479
5   GBC Ibimaster 500 Manual ProClick Binding System    19024.500
6               Hewlett Packard LaserJet 3310 Copier    18839.686
7  HP Designjet T520 Inkjet Large Format Printer ...    18374.895
8          GBC DocuBind P400 Electric Binding System    17965.068
9        High Speed Automatic Electric Letter Opener    17030.312

In [105]:
#Top categories by sales
query = """
SELECT Category, SUM(Sales) AS total_sales
FROM superstore
GROUP BY Category
ORDER BY total_sales DESC;
"""

pd.read_sql(query, conn)

          Category  total_sales
0       Technology  836154.0330
1        Furniture  741999.7953
2  Office Supplies  719047.0320

### Business Queries

The following queries answer a few common business questions using the sales dataset.

In [106]:
#Monthly sales trend
query = """
SELECT substr("Order Date", 4, 7) AS month, ROUND(SUM(Sales), 2) AS total_sales
FROM superstore
GROUP BY month
ORDER BY month;
"""

pd.read_sql(query, conn)

      month  total_sales
0     /2014     91397.31
1     /2015     65598.66
2     /2016    124719.23
3     /2017    121493.16
4    0/2014     28717.51
..      ...          ...
127  8/2017     31488.16
128  9/2014     26499.38
129  9/2015     17472.56
130  9/2016     19036.17
131  9/2017     36622.22

[132 rows x 2 columns]

In [107]:
#Top 10 Customers by Sales
query = """
SELECT "Customer Name", ROUND(SUM(Sales), 2) AS total_sales
FROM superstore
GROUP BY "Customer Name"
ORDER BY total_sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

        Customer Name  total_sales
0         Sean Miller     25043.05
1        Tamara Chand     19052.22
2        Raymond Buch     15117.34
3        Tom Ashbrook     14595.62
4       Adrian Barton     14473.57
5        Ken Lonsdale     14175.23
6        Sanjit Chand     14142.33
7        Hunter Lopez     12873.30
8        Sanjit Engle     12209.44
9  Christopher Conant     12129.07

### Data Validation

A few validation queries are executed to verify the quality of the imported dataset before completing the analysis.

In [108]:
#Total records
query = """SELECT COUNT(*) AS total_records FROM superstore;"""
pd.read_sql(query, conn)

   total_records
0           9994

In [109]:
#Missing customer ID
query = """SELECT COUNT(*) AS missing_customer_ids FROM superstore WHERE "Customer ID" IS NULL;"""
pd.read_sql(query, conn)

   missing_customer_ids
0                     0

In [110]:
#distinct categories
query = """SELECT COUNT(DISTINCT Category) AS total_categories FROM superstore;"""
pd.read_sql(query, conn)

   total_categories
0                 3

## Part B - Database Implementation

This part follows the database schema provided in the assignment document. The required tables, constraints, indexes, and sample records are created before solving the SQL questions.

In [117]:
schema ="""
CREATE TABLE customers ( 
    customer_id   INT           PRIMARY KEY, 
    first_name    VARCHAR(50)   NOT NULL, 
    last_name     VARCHAR(50)   NOT NULL, 
    email         VARCHAR(100)  UNIQUE NOT NULL, 
    city          VARCHAR(50)   NOT NULL, 
    state         VARCHAR(50)   NOT NULL, 
    join_date     DATE          NOT NULL, 
    is_premium    BOOLEAN       DEFAULT FALSE 
); 
 
-- Index for filtering by city/state 
CREATE INDEX idx_customers_city ON customers(city); 
CREATE INDEX idx_customers_state ON customers(state);

CREATE TABLE products ( 
    product_id    INT           PRIMARY KEY, 
    product_name  VARCHAR(100)  NOT NULL, 
    category      VARCHAR(50)   NOT NULL, 
    brand         VARCHAR(50)   NOT NULL, 
    unit_price    DECIMAL(10,2) NOT NULL  CHECK (unit_price > 0), 
    stock_qty     INT           NOT NULL  DEFAULT 0  CHECK (stock_qty >= 0) 
); 
 
-- Index for filtering by category 
CREATE INDEX idx_products_category ON products(category); 

CREATE TABLE orders ( 
    order_id      INT           PRIMARY KEY, 
    customer_id   INT           NOT NULL, 
    order_date    DATE          NOT NULL, 
    status        VARCHAR(20)   NOT NULL  DEFAULT 'Pending' 
                  CHECK (status IN ('Pending','Shipped','Delivered','Cancelled')), 
    total_amount  DECIMAL(12,2) NOT NULL  CHECK (total_amount >= 0), 
     
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id) 
); 
 
-- Index for date-based filtering and sorting 
CREATE INDEX idx_orders_date ON orders(order_date); 
CREATE INDEX idx_orders_status ON orders(status); 

CREATE TABLE order_items ( 
    item_id       INT           PRIMARY KEY, 
    order_id      INT           NOT NULL, 
    product_id    INT           NOT NULL, 
    quantity      INT           NOT NULL  CHECK (quantity > 0), 
    unit_price    DECIMAL(10,2) NOT NULL  CHECK (unit_price > 0), 
    discount_pct  DECIMAL(5,2)  DEFAULT 0 CHECK (discount_pct BETWEEN 0 AND 100), 
     
    FOREIGN KEY (order_id)   REFERENCES orders(order_id), 
    FOREIGN KEY (product_id) REFERENCES products(product_id) 
);
"""

cursor.executescript(schema) 
conn.commit()
print("Database schema created successfully.")

Database schema created successfully.

In [118]:
#Now inserting sample data provided

sample_data = """
-- ========== INSERT: customers ========== 
INSERT INTO customers VALUES 
(101, 'Aarav',  'Sharma', 'aarav.s@email.com',  'Mumbai',    'Maharashtra', '2024-01-15', TRUE), 
(102, 'Priya',  'Patel',  'priya.p@email.com',  'Ahmedabad', 'Gujarat',     '2024-02-20', FALSE), 
(103, 'Rohan',  'Gupta',  'rohan.g@email.com',  'Delhi',     'Delhi',       '2024-03-10', TRUE), 
(104, 'Sneha',  'Reddy',  'sneha.r@email.com',  'Hyderabad', 'Telangana',   '2024-04-05', FALSE), 
(105, 'Vikram', 'Singh',  'vikram.s@email.com', 'Jaipur',    'Rajasthan',   '2024-05-12', TRUE), 
(106, 'Ananya', 'Iyer',   'ananya.i@email.com', 'Chennai',   'Tamil Nadu',  '2024-06-18', FALSE), 
(107, 'Karan',  'Mehta',  'karan.m@email.com',  'Pune',      'Maharashtra', '2024-07-22', TRUE), 
(108, 'Divya',  'Nair',   'divya.n@email.com',  'Kochi',     'Kerala',      '2024-08-30', FALSE); 

-- ========== INSERT: products ========== 
INSERT INTO products VALUES 
(201, 'Wireless Earbuds',     'Electronics', 'BoAt',          1499.00, 250), 
(202, 'Cotton T-Shirt',       'Clothing',    'Levis',         799.00,  500), 
(203, 'Smart Watch',          'Electronics', 'Noise',         2999.00, 150), 
(204, 'Running Shoes',        'Clothing',    'Nike',          4599.00, 120), 
(205, 'Bluetooth Speaker',    'Electronics', 'JBL',           3499.00, 200), 
(206, 'Bedsheet Set',         'Home',        'Spaces',        1299.00, 300), 
(207, 'Laptop Stand',         'Electronics', 'AmazonBasics',  899.00,  180), 
(208, 'Cushion Covers (Set)', 'Home',        'HomeCenter',    599.00,  400); 

-- ========== INSERT: orders ========== 
INSERT INTO orders VALUES 
(1001, 101, '2024-08-01', 'Delivered',  4498.00), 
(1002, 102, '2024-08-03', 'Delivered',  799.00), 
(1003, 103, '2024-08-05', 'Shipped',    7498.00), 
(1004, 101, '2024-08-10', 'Delivered',  3499.00), 
(1005, 104, '2024-08-12', 'Cancelled',  2999.00), 
(1006, 105, '2024-08-15', 'Delivered',  5898.00), 
(1007, 106, '2024-08-18', 'Pending',    1299.00), 
(1008, 103, '2024-08-20', 'Delivered',  899.00), 
(1009, 107, '2024-08-25', 'Shipped',    6098.00), 
(1010, 108, '2024-08-28', 'Delivered',  1598.00); 

-- ========== INSERT: order_items ========== 
INSERT INTO order_items VALUES 
(5001, 1001, 201, 2, 1499.00, 0), 
(5002, 1001, 207, 1, 899.00,  10), 
(5003, 1002, 202, 1, 799.00,  0), 
(5004, 1003, 203, 1, 2999.00, 0), 
(5005, 1003, 204, 1, 4599.00, 5), 
(5006, 1004, 205, 1, 3499.00, 0), 
(5007, 1005, 203, 1, 2999.00, 0), 
(5008, 1006, 201, 1, 1499.00, 10), 
(5009, 1006, 204, 1, 4599.00, 5), 
(5010, 1007, 206, 1, 1299.00, 0), 
(5011, 1008, 207, 1, 899.00,  0), 
(5012, 1009, 205, 1, 3499.00, 0), 
(5013, 1009, 208, 2, 599.00,  15), 
(5014, 1010, 206, 1, 1299.00, 0), 
(5015, 1010, 208, 1, 599.00,  0); 

"""

cursor.executescript(sample_data)
conn.commit()
print("Sample data inserted successfully.")

Sample data inserted successfully.

### Verifying the Database

The following queries are used to verify that all tables have been created successfully and the sample data has been inserted correctly.

In [ ]:
#Total Customer Count
query = """SELECT COUNT(*) AS total_customers FROM customers;"""
pd.read_sql(query, conn)

   total_customers
0                8

In [120]:
#Total Product Count
query = """SELECT COUNT(*) AS total_products FROM products;"""
pd.read_sql(query, conn)

   total_products
0               8

In [121]:
#Total Orders Count
query = """SELECT COUNT(*) AS total_orders FROM orders;"""
pd.read_sql(query, conn)

   total_orders
0            10

In [122]:
#Total Order Items COunt
query = """SELECT COUNT(*) AS total_order_items FROM order_items;"""
pd.read_sql(query, conn)

   total_order_items
0                 15

In [123]:
#available tables
query = """SELECT name FROM sqlite_master WHERE type='table';"""
pd.read_sql(query, conn)

              name
0  sqlite_sequence
1       superstore
2        customers
3         products
4           orders
5      order_items

### Section A - SQL Basics (SELECT, Constraints, Primary Keys)

This section covers basic SQL queries along with primary keys and database constraints defined in the given schema.

### **Q1. Write a query to display all columns and rows from the customer's table.**

In [124]:
query = """SELECT * FROM customers;"""
pd.read_sql(query, conn)

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,102,Priya,Patel,priya.p@email.com,Ahmedabad,Gujarat,2024-02-20,0
2,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1
3,104,Sneha,Reddy,sneha.r@email.com,Hyderabad,Telangana,2024-04-05,0
4,105,Vikram,Singh,vikram.s@email.com,Jaipur,Rajasthan,2024-05-12,1
5,106,Ananya,Iyer,ananya.i@email.com,Chennai,Tamil Nadu,2024-06-18,0
6,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1
7,108,Divya,Nair,divya.n@email.com,Kochi,Kerala,2024-08-30,0

### **Q2. Retrieve only the first_name, last_name, and city of all customers.**

In [126]:
query = """SELECT first_name, last_name, city FROM customers;"""
pd.read_sql(query, conn)

  first_name last_name       city
0      Aarav    Sharma     Mumbai
1      Priya     Patel  Ahmedabad
2      Rohan     Gupta      Delhi
3      Sneha     Reddy  Hyderabad
4     Vikram     Singh     Jaipur
5     Ananya      Iyer    Chennai
6      Karan     Mehta       Pune
7      Divya      Nair      Kochi

### **Q3. List all unique categories available in the products table.**

In [127]:
query = """SELECT DISTINCT category FROM products;"""
pd.read_sql(query, conn)

      category
0     Clothing
1  Electronics
2         Home

### **Q4. Identify the Primary Key of each table in the schema. Explain why a Primary Key must be unique and NOT NULL.**

**Answer:**

| Table | Primary Key |
|--------|-------------|
| customers | customer_id |
| products | product_id |
| orders | order_id |
| order_items | item_id |

A primary key uniquely identifies every record in a table. It must always contain a unique value and cannot be NULL because it is used to identify each row.

In [128]:
query = """PRAGMA table_info(customers);"""
pd.read_sql(query, conn)

   cid         name          type  notnull dflt_value  pk
0    0  customer_id           INT        0        NaN   1
1    1   first_name   VARCHAR(50)        1        NaN   0
2    2    last_name   VARCHAR(50)        1        NaN   0
3    3        email  VARCHAR(100)        1        NaN   0
4    4         city   VARCHAR(50)        1        NaN   0
5    5        state   VARCHAR(50)        1        NaN   0
6    6    join_date          DATE        1        NaN   0
7    7   is_premium       BOOLEAN        0      FALSE   0

In [129]:
query = """PRAGMA table_info(products);"""
pd.read_sql(query, conn)

   cid          name           type  notnull dflt_value  pk
0    0    product_id            INT        0        NaN   1
1    1  product_name   VARCHAR(100)        1        NaN   0
2    2      category    VARCHAR(50)        1        NaN   0
3    3         brand    VARCHAR(50)        1        NaN   0
4    4    unit_price  DECIMAL(10,2)        1        NaN   0
5    5     stock_qty            INT        1          0   0

In [130]:
query = """PRAGMA table_info(orders);"""
pd.read_sql(query, conn)

   cid          name           type  notnull dflt_value  pk
0    0      order_id            INT        0        NaN   1
1    1   customer_id            INT        1        NaN   0
2    2    order_date           DATE        1        NaN   0
3    3        status    VARCHAR(20)        1  'Pending'   0
4    4  total_amount  DECIMAL(12,2)        1        NaN   0

In [131]:
query = """PRAGMA table_info(order_items);"""
pd.read_sql(query, conn)

   cid          name           type  notnull dflt_value  pk
0    0       item_id            INT        0        NaN   1
1    1      order_id            INT        1        NaN   0
2    2    product_id            INT        1        NaN   0
3    3      quantity            INT        1        NaN   0
4    4    unit_price  DECIMAL(10,2)        1        NaN   0
5    5  discount_pct   DECIMAL(5,2)        0          0   0

### **Q5. What constraints are applied to the email column in the customers table? What would happen if you tried to insert a duplicate email?**

**Answer:**

The **email** column has the following constraints:

- `NOT NULL`
- `UNIQUE`

If a duplicate email is inserted, SQLite raises a **UNIQUE constraint failed** error and the record is not inserted.

In [132]:
query = """
INSERT INTO customers
VALUES (109, 'Rahul', 'Joshi', 'aarav.s@email.com', 'Nagpur', 'Maharashtra', '2024-09-01', TRUE);
"""

try:
    cursor.execute(query)
    conn.commit()
    print("Record inserted successfully.")
#Exception Handling for best practice
except Exception as e:
    print(e)

UNIQUE constraint failed: customers.email

### **Q6. Try inserting a product with unit_price = -50. What happens and which constraint prevents it? Write both the INSERT statement and explain the error.**

**Answer:**

The record is rejected because the **CHECK (unit_price > 0)** constraint does not allow negative values. SQLite returns a **CHECK constraint failed** error, ensuring that only valid product prices are stored in the table.

In [133]:
query = """
INSERT INTO products
VALUES ( 209, 'Sample Product', 'Electronics', 'ABC', -50, 20 );
"""

try:
    cursor.execute(query)
    conn.commit()
    print("Record inserted successfully.")
#Exception Handling
except Exception as e:
    print(e)

CHECK constraint failed: unit_price > 0

### Section B - Filtering & Optimization (WHERE, Indexes)

This section focuses on filtering records using the `WHERE` clause and understanding how indexes help improve query performance.

### **Q7. Retrieve all orders with status = 'Delivered'.**

In [134]:
query = """SELECT * FROM orders WHERE status = 'Delivered';"""
pd.read_sql(query, conn)

   order_id  customer_id  order_date     status  total_amount
0      1001          101  2024-08-01  Delivered          4498
1      1002          102  2024-08-03  Delivered           799
2      1004          101  2024-08-10  Delivered          3499
3      1006          105  2024-08-15  Delivered          5898
4      1008          103  2024-08-20  Delivered           899
5      1010          108  2024-08-28  Delivered          1598

### **Q8. Find all products in the 'Electronics' category with a unit_price greater than ₹2000.**

In [135]:
query = """
SELECT * FROM products
WHERE category = 'Electronics' AND unit_price > 2000;
"""

pd.read_sql(query, conn)

   product_id       product_name     category  brand  unit_price  stock_qty
0         203        Smart Watch  Electronics  Noise        2999        150
1         205  Bluetooth Speaker  Electronics    JBL        3499        200

### **Q9. List all customers who joined in the year 2024 and belong to the state 'Maharashtra'.**

In [136]:
query = """
SELECT * FROM customers
WHERE state = 'Maharashtra' AND join_date BETWEEN '2024-01-01' AND '2024-12-31';
"""

pd.read_sql(query, conn)

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1

### **Q10. Find all orders placed between '2024-08-10' and '2024-08-25' (inclusive) that are NOT cancelled.**

In [137]:
query = """
SELECT * FROM orders
WHERE order_date BETWEEN '2024-08-10' AND '2024-08-25' AND status <> 'Cancelled';
"""

pd.read_sql(query, conn)

   order_id  customer_id  order_date     status  total_amount
0      1004          101  2024-08-10  Delivered          3499
1      1006          105  2024-08-15  Delivered          5898
2      1007          106  2024-08-18    Pending          1299
3      1008          103  2024-08-20  Delivered           899
4      1009          107  2024-08-25    Shipped          6098

### **Q11. Explain what the index `idx_orders_date` does. How would it improve the performance of a query that filters orders by `order_date`? Write a sample query that would benefit from this index.**

**Answer:**

The `idx_orders_date` index is created on the **order_date** column. It helps SQLite locate matching records faster when filtering or sorting using the order date, instead of scanning the entire table.

**Sample Query**

In [138]:
query = """
SELECT * FROM orders
WHERE order_date = '2024-08-15';
"""

pd.read_sql(query, conn)

   order_id  customer_id  order_date     status  total_amount
0      1006          105  2024-08-15  Delivered          5898

### **Q12. If you run: `SELECT * FROM customers WHERE YEAR(join_date) = 2024;` would the index on `join_date` be used? Explain why or why not, and rewrite the query to be index-friendly (SARGable).**

**Answer:**

No. Applying a function like `YEAR()` on the indexed column prevents the database from using the index efficiently.

Instead, filter the date using a range so that the index can be used.

In [139]:
query = """
SELECT * FROM customers
WHERE join_date BETWEEN '2024-01-01' AND '2024-12-31';
"""

pd.read_sql(query, conn)

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,102,Priya,Patel,priya.p@email.com,Ahmedabad,Gujarat,2024-02-20,0
2,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1
3,104,Sneha,Reddy,sneha.r@email.com,Hyderabad,Telangana,2024-04-05,0
4,105,Vikram,Singh,vikram.s@email.com,Jaipur,Rajasthan,2024-05-12,1
5,106,Ananya,Iyer,ananya.i@email.com,Chennai,Tamil Nadu,2024-06-18,0
6,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1
7,108,Divya,Nair,divya.n@email.com,Kochi,Kerala,2024-08-30,0

### Section C - Aggregation (GROUP BY, SUM, COUNT, AVG, MIN, MAX)

This section uses aggregate functions to summarize the data and generate meaningful business information.

### **Q13. Count the total number of orders in the orders table.**

In [140]:
query = """SELECT COUNT(*) AS total_orders FROM orders;"""
pd.read_sql(query, conn)

   total_orders
0            10

### **Q14. Find the total revenue (SUM of total_amount) from all 'Delivered' orders.**

In [141]:
query = """
SELECT SUM(total_amount) AS total_revenue FROM orders
WHERE status = 'Delivered';
"""

pd.read_sql(query, conn)

   total_revenue
0          17191

### **Q15. Calculate the average unit_price of products in each category.**

In [142]:
query = """
SELECT category, ROUND(AVG(unit_price), 2) AS average_unit_price
FROM products
GROUP BY category;
"""

pd.read_sql(query, conn)

      category  average_unit_price
0     Clothing              2699.0
1  Electronics              2224.0
2         Home               949.0

### **Q16. For each order status, find the count of orders and the total revenue. Sort the result by total revenue in descending order.**

In [143]:
query = """
SELECT status, COUNT(order_id) AS total_orders, SUM(total_amount) AS total_revenue
FROM orders
GROUP BY status
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conn)

      status  total_orders  total_revenue
0  Delivered             6          17191
1    Shipped             2          13596
2  Cancelled             1           2999
3    Pending             1           1299

### **Q17. Find the most expensive (MAX) and cheapest (MIN) product in each category.**

In [144]:
query = """
SELECT category, MAX(unit_price) AS highest_price, MIN(unit_price) AS lowest_price
FROM products
GROUP BY category;
"""

pd.read_sql(query, conn)

      category  highest_price  lowest_price
0     Clothing           4599           799
1  Electronics           3499           899
2         Home           1299           599

### **Q18. List all product categories where the average unit_price is greater than ₹2000. (Hint: Use HAVING clause)**

In [145]:
query = """
SELECT category, ROUND(AVG(unit_price), 2) AS average_unit_price
FROM products
GROUP BY category
HAVING AVG(unit_price) > 2000;
"""

pd.read_sql(query, conn)

      category  average_unit_price
0     Clothing              2699.0
1  Electronics              2224.0

### Section D - Joins & Relationships

This section demonstrates how different types of joins are used to combine data from multiple tables and understand the relationships between them.

### **Q19. Write an INNER JOIN query to display each order along with the customer's first_name and last_name. Show: order_id, order_date, first_name, last_name, total_amount.**

In [146]:
query = """
SELECT o.order_id, o.order_date, c.first_name, c.last_name, o.total_amount
FROM orders o
INNER JOIN customers c
ON o.customer_id = c.customer_id;
"""

pd.read_sql(query, conn)

   order_id  order_date first_name last_name  total_amount
0      1001  2024-08-01      Aarav    Sharma          4498
1      1002  2024-08-03      Priya     Patel           799
2      1003  2024-08-05      Rohan     Gupta          7498
3      1004  2024-08-10      Aarav    Sharma          3499
4      1005  2024-08-12      Sneha     Reddy          2999
5      1006  2024-08-15     Vikram     Singh          5898
6      1007  2024-08-18     Ananya      Iyer          1299
7      1008  2024-08-20      Rohan     Gupta           899
8      1009  2024-08-25      Karan     Mehta          6098
9      1010  2024-08-28      Divya      Nair          1598

### **Q20. Using a LEFT JOIN, list ALL customers and their orders (if any). Customers with no orders should still appear with NULL values for order columns.**

In [147]:
query = """
SELECT c.customer_id, c.first_name, c.last_name, o.order_id, o.order_date, o.status
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id;
"""

pd.read_sql(query, conn)

   customer_id first_name last_name  order_id  order_date     status
0          101      Aarav    Sharma      1001  2024-08-01  Delivered
1          101      Aarav    Sharma      1004  2024-08-10  Delivered
2          102      Priya     Patel      1002  2024-08-03  Delivered
3          103      Rohan     Gupta      1003  2024-08-05    Shipped
4          103      Rohan     Gupta      1008  2024-08-20  Delivered
5          104      Sneha     Reddy      1005  2024-08-12  Cancelled
6          105     Vikram     Singh      1006  2024-08-15  Delivered
7          106     Ananya      Iyer      1007  2024-08-18    Pending
8          107      Karan     Mehta      1009  2024-08-25    Shipped
9          108      Divya      Nair      1010  2024-08-28  Delivered

### **Q21. Write a query using JOINs across three tables (orders → order_items → products) to show: order_id, product_name, quantity, unit_price, and discount_pct for each order item.**

In [148]:
query = """
SELECT o.order_id, p.product_name, oi.quantity, oi.unit_price, oi.discount_pct
FROM orders o
INNER JOIN order_items oi
ON o.order_id = oi.order_id
INNER JOIN products p
ON oi.product_id = p.product_id;
"""

pd.read_sql(query, conn)

    order_id          product_name  quantity  unit_price  discount_pct
0       1001      Wireless Earbuds         2        1499             0
1       1001          Laptop Stand         1         899            10
2       1002        Cotton T-Shirt         1         799             0
3       1003           Smart Watch         1        2999             0
4       1003         Running Shoes         1        4599             5
5       1004     Bluetooth Speaker         1        3499             0
6       1005           Smart Watch         1        2999             0
7       1006      Wireless Earbuds         1        1499            10
8       1006         Running Shoes         1        4599             5
9       1007          Bedsheet Set         1        1299             0
10      1008          Laptop Stand         1         899             0
11      1009     Bluetooth Speaker         1        3499             0
12      1009  Cushion Covers (Set)         2         599            15
13      1010          Bedsheet Set         1        1299             0
14      1010  Cushion Covers (Set)         1         599             0

### **Q22. Explain the difference between LEFT JOIN and RIGHT JOIN with an example from this schema. When would you use a FULL OUTER JOIN?**

**Answer:**

- **LEFT JOIN** returns all records from the left table and matching records from the right table. If there is no matching record, NULL values are returned for the right table.

- **RIGHT JOIN** returns all records from the right table and matching records from the left table. SQLite does not support `RIGHT JOIN` directly.

- **FULL OUTER JOIN** returns all matching records from both tables. If a record exists only in one table, the missing values from the other table are returned as NULL. SQLite also does not support `FULL OUTER JOIN` directly.

**Example**

- `customers LEFT JOIN orders` returns all customers, including those who have not placed any orders.
- A `FULL OUTER JOIN` would be useful if we wanted to display every customer and every order, even when there is no matching record on either side.

### **Q23. Identify all Foreign Key relationships in the schema. Explain what would happen if you tried to insert an order with customer_id = 999 (which doesn't exist in customers).**

**Foreign Key Relationships**

| Parent Table | Child Table | Foreign Key |
|--------------|-------------|-------------|
| customers | orders | customer_id |
| orders | order_items | order_id |
| products | order_items | product_id |

If an order is inserted with `customer_id = 999` and that customer does not exist in the `customers` table, the database will reject the insert because of the **FOREIGN KEY** constraint. This prevents invalid references and helps maintain referential integrity.

In [151]:
query = """
INSERT INTO orders
VALUES ( 1011, 999, '2024-09-01', 'Pending', 1598.00);
"""

try:
    cursor.execute(query)
    conn.commit()
    print("Record inserted successfully.")
#Exception Handling
except Exception as e:
    print(e)

UNIQUE constraint failed: orders.order_id

### Section E - Advanced Concepts (CASE, ACID, Transactions)

This section covers conditional statements, database transactions, and the ACID properties that help maintain data consistency and reliability.

### **Q24. Write a query using CASE to classify products into price tiers:**

- Budget → unit_price < 1000
- Mid-Range → unit_price BETWEEN 1000 AND 3000
- Premium → unit_price > 3000

**Display:** product_name, unit_price, price_tier.

In [152]:
query = """
SELECT product_name, unit_price,
CASE
    WHEN unit_price < 1000 THEN 'Budget'
    WHEN unit_price BETWEEN 1000 AND 3000 THEN 'Mid-Range'
    ELSE 'Premium'
END AS price_tier
FROM products;
"""

pd.read_sql(query, conn)

           product_name  unit_price price_tier
0      Wireless Earbuds        1499  Mid-Range
1        Cotton T-Shirt         799     Budget
2           Smart Watch        2999  Mid-Range
3         Running Shoes        4599    Premium
4     Bluetooth Speaker        3499    Premium
5          Bedsheet Set        1299  Mid-Range
6          Laptop Stand         899     Budget
7  Cushion Covers (Set)         599     Budget

### **Q25. Using a CASE statement inside an aggregate function, count how many orders are 'Delivered' vs 'Not Delivered' (all other statuses). Display the result in a single row.**

In [153]:
query = """
SELECT 
SUM(CASE WHEN status = 'Delivered' THEN 1 ELSE 0 END) AS delivered_orders, 
SUM(CASE WHEN status <> 'Delivered' THEN 1 ELSE 0 END) AS not_delivered_orders
FROM orders;
"""

pd.read_sql(query, conn)

   delivered_orders  not_delivered_orders
0                 6                     5

### **Q26. Explain each letter of ACID. Give a real-world example showing why each property is important.**

**Answer:**

**A – Atomicity**

A transaction is treated as a single unit of work. Either all operations are completed successfully or none of them are applied.

**Example:** During a bank transfer, if money is deducted from one account but cannot be credited to another account, the entire transaction is rolled back.

---

**C – Consistency**

A transaction should always move the database from one valid state to another without violating any constraints.

**Example:** A product order cannot reference a customer who does not exist because of the foreign key constraint.

---

**I – Isolation**

Multiple transactions running at the same time should not interfere with one another.

**Example:** Two customers placing orders simultaneously should not affect each other's transaction.

---

**D – Durability**

Once a transaction is committed, the changes remain saved even if the system crashes immediately afterwards.

**Example:** After an online payment is marked successful, the transaction remains recorded even if the server restarts.

### **Q27. Write a SQL transaction that does the following atomically:**

1. Insert a new order (`order_id = 1011`)
2. Insert two order items
3. Update the stock quantity
4. Roll back the transaction if any step fails; otherwise commit the transaction.

In [155]:
transaction = """
BEGIN TRANSACTION;

INSERT INTO orders
VALUES ( 1011, 102, '2024-09-05', 'Pending', 1598.00);

INSERT INTO order_items
VALUES ( 5016, 1011, 206, 1, 1299.00, 0);

INSERT INTO order_items
VALUES ( 5017, 1011, 208, 1, 599.00, 0);

UPDATE products
SET stock_qty = stock_qty - 1
WHERE product_id = 206;

UPDATE products
SET stock_qty = stock_qty - 1
WHERE product_id = 208;

COMMIT;
"""

try:
    cursor.executescript(transaction)
    conn.commit()
    print("Transaction completed successfully.")

#exception handling for roll back
except Exception as e:
    conn.rollback()
    print("Transaction failed.")
    print(e)

Transaction failed.
UNIQUE constraint failed: orders.order_id

# Overall Summary

## Part A – Sales Data Analysis

- Loaded the Superstore dataset into a SQLite database.
- Explored the dataset by checking its schema, sample records, data types, missing values, and duplicate records.
- Applied SQL queries using filtering, aggregation, sorting, and grouping techniques.
- Solved business-related queries including monthly sales trends, top products, top customers, and data validation.
- Summarized the analysis using brief business insights based on the query results.

---

## Part B – Database Implementation

- Created the database schema using the tables and constraints provided in the assignment.
- Applied primary keys, foreign keys, indexes, and validation constraints.
- Loaded the sample data into all four tables.
- Verified the database structure and inserted records before executing the SQL queries.

---

## Section-wise Summary

### Section A
- Practiced basic `SELECT` statements and explored table structures.
- Understood the use of primary keys and common database constraints.

### Section B
- Retrieved records using different filtering conditions.
- Learned how indexes improve query performance and wrote index-friendly queries.

### Section C
- Used aggregate functions such as `COUNT()`, `SUM()`, `AVG()`, `MIN()`, and `MAX()`.
- Summarized data using `GROUP BY` and `HAVING`.

### Section D
- Combined data from multiple tables using joins.
- Understood table relationships and foreign key constraints.

### Section E
- Used `CASE` expressions for conditional logic.
- Learned the ACID properties of transactions.
- Executed a transaction involving inserts and updates while maintaining database consistency.

---

## Conclusion

This assignment helped strengthen my understanding of SQL fundamentals and practical database operations. Along with completing the sales data analysis using the provided Superstore dataset, I also implemented the database schema and solved all 27 SQL questions based on the assignment document.

During the weekly mentor meeting, it was suggested to follow the SQL questions provided in the assignment document. At the same time, the LMS objective required analysis of the provided sales dataset. To address both requirements, I completed the sales analysis using the Superstore dataset in **Part A** and implemented the database schema with all 27 questions in **Part B**. This approach helped me cover the complete assignment while practicing both business-oriented SQL analysis and core database concepts in a structured manner.